name: Dhankuber
description: A Flutter project for managing FD/RD investments.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  firebase_core: ^3.13.1 # Pinned to exact version
  firebase_auth: ^5.5.4 # Pinned to exact version
  cloud_firestore: ^5.6.8 # Already pinned
  firebase_analytics: ^11.4.6 # Pinned to exact version
  firebase_crashlytics: ^4.3.6 # Pinned to exact version
  flutter_secure_storage: ^9.2.2
  dio: ^5.7.0
  onesignal_flutter: ^5.2.0
  lottie: ^3.1.2
  flutter_svg: ^2.0.10
  local_auth: ^2.3.0
  webview_flutter: ^4.8.0
  webview_flutter_android: ^4.7.0
  connectivity_plus: ^6.0.5
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.1 # Added for native splash screen

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/logo.png
    - assets/icons/
    - assets/lottie/
    - assets/lottie/tick.json
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#F5F7FA" # Matches AppColors.background (assumed to be #F5F7FA, adjust if different)
  image: assets/images/logo.png
  android: true
  ios: true
  android_12:
    image: assets/images/logo.png
    color: "#F5F7FA"