// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCYXlzmW9NWY6afgrHVx-lAbJ21PkWYY8',
    appId: '1:1019796244455:web:b6d54d64e6a59dd0911f42',
    messagingSenderId: '1019796244455',
    projectId: 'dhan-kuber-app',
    authDomain: 'dhan-kuber-app.firebaseapp.com',
    storageBucket: 'dhan-kuber-app.firebasestorage.app',
    measurementId: 'G-TNJTQH4DKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpFerdPmNesfEGsCXczYjs3uiBXuFxqJE',
    appId: '1:1019796244455:android:895264dab5460722911f42',
    messagingSenderId: '1019796244455',
    projectId: 'dhan-kuber-app',
    storageBucket: 'dhan-kuber-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApvR5YqMHZWG2YnQLc-4QzyGFOeHkQJis',
    appId: '1:1019796244455:ios:38da71d433742ffc911f42',
    messagingSenderId: '1019796244455',
    projectId: 'dhan-kuber-app',
    storageBucket: 'dhan-kuber-app.firebasestorage.app',
    iosBundleId: 'com.app.dhankuber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApvR5YqMHZWG2YnQLc-4QzyGFOeHkQJis',
    appId: '1:1019796244455:ios:38da71d433742ffc911f42',
    messagingSenderId: '1019796244455',
    projectId: 'dhan-kuber-app',
    storageBucket: 'dhan-kuber-app.firebasestorage.app',
    iosBundleId: 'com.app.dhankuber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCYXlzmW9NWY6afgrHVx-lAbJ21PkWYY8',
    appId: '1:1019796244455:web:b6b30b2d5dec0f69911f42',
    messagingSenderId: '1019796244455',
    projectId: 'dhan-kuber-app',
    authDomain: 'dhan-kuber-app.firebaseapp.com',
    storageBucket: 'dhan-kuber-app.firebasestorage.app',
    measurementId: 'G-HJHC6K2TV0',
  );
}
